### ISSUE TITLE
setup brain chris instance

### ISSUE THREAD

**Issue by NicolasRannou** [FNNDSC/projectman#44]
'brain.chpc.ac.za', user: rpienaar.

A good exercise to make sure the wiki is up to date.

**Comment by NicolasRannou** [comment]
We need to contact the help desk, might be a firewall issue: port 443 is blocked.

In the meanwhile, using regular http connection.

```
nico@vpn-17218216-151:~$ telnet brain.chpc.ac.za 80
Trying 196.24.44.34...
Connected to brain.chpc.ac.za.
Escape character is '^]'.
^C
Connection closed by foreign host.
nico@vpn-17218216-151:~$ telnet brain.chpc.ac.za 443
Trying 196.24.44.34...
telnet: connect to address 196.24.44.34: Operation timed out
telnet: Unable to connect to remote host
```

**Comment by NicolasRannou** [comment]
sudo su was not passwordless for chris user

updated the wiki: 
http://durban/wiki/index.php/ChRISMEGABUNDLE#If_a_VM_is_given_with_Ubuntu_already_installed

**Comment by NicolasRannou** [comment]
findsession plugin was there, which makes everything crash because can not generate XML output.

```
$> tail -f /var/log/apache2/error.log
[Fri Mar 06 10:17:45.850659 2015] [:error] [pid 30294] [client 134.174.21.27:4879] PHP Warning:  SimpleXMLElement::__construct(): Entity: line 1: parser error : Start tag expected, '&lt;' not found in /home/chris/src/chrisreloaded/controller/plugin.controller.php on line 164, referer: http://brain.chpc.ac.za/
[Fri Mar 06 10:17:45.850995 2015] [:error] [pid 30294] [client 134.174.21.27:4879] PHP Warning:  SimpleXMLElement::__construct(): Traceback (most recent call last):  File &quot;/home/chris/src/chrisreloaded/plugins/ in /home/chris/src/chrisreloaded/controller/plugin.controller.php on line 164, referer: http://brain.chpc.ac.za/
[Fri Mar 06 10:17:45.851155 2015] [:error] [pid 30294] [client 134.174.21.27:4879] PHP Warning:  SimpleXMLElement::__construct(): ^ in /home/chris/src/chrisreloaded/controller/plugin.controller.php on line 164, referer: http://brain.chpc.ac.za/
[Fri Mar 06 10:17:45.851819 2015] [:error] [pid 30294] [client 134.174.21.27:4879] PHP Fatal error:  Uncaught exception 'Exception' with message 'String could not be parsed as XML' in /home/chris/src/chrisreloaded/controller/plugin.controller.php:164\nStack trace:\n#0 /home/chris/src/chrisreloaded/controller/plugin.controller.php(164): SimpleXMLElement->__construct('Traceback (most...')\n#1 /home/chris/src/chrisreloaded/view/plugin.view.php(82): PluginC::getUI('findsession')\n#2 /home/chris/src/chrisreloaded/controller/plugin.controller.php(72): PluginV::getHTML(Array)\n#3 /home/chris/src/chrisreloaded/index.php(73): PluginC::getHTML()\n#4 /home/chris/src/chrisreloaded/index.php(195): homePage()\n#5 {main}\n  thrown in /home/chris/src/chrisreloaded/controller/plugin.controller.php on line 164, referer: http://brain.chpc.ac.za/
```

Deeper investigation:

```
chris@brain:~/src/chrisreloaded/plugins/findsession$ ./findsession --xml
Traceback (most recent call last):
  File "./findsession", line 110, in <module>
    plugin.add_parameter('Advanced', Plugin.STRING, '--findsessionscript', action='store', dest='FindSessionScript', default=plugin.envVars['ENV_FINDSESSION_SCRIPT'], help='The find session script')
KeyError: 'ENV_FINDSESSION_SCRIPT'
``
```

**Comment by NicolasRannou** [comment]
need to hook up a chris_push between BCH and Brain:
1- passwordless shh
2- email service
3- add targets in both configurations

**Comment by rudolphpienaar** [comment]
Good work, Nico...

I'll look into the passwordless ssh and email right now...

**Comment by NicolasRannou** [comment]
ZIP package on brain VM was missing...

**Comment by NicolasRannou** [comment]
freesurfer was missing

**Comment by NicolasRannou** [comment]
neuro-fs script must be modified:

```
-export PACKAGEDIR=/neuro/arch/${HOSTTYPE}-${OS}/packages
+export PACKAGEDIR=/lustre/SCRATCH5/cubic/chris/packages
```

**Comment by NicolasRannou** [comment]
libxmu not available anymore on ubuntu, use:
sudo apt-get install libxmu6

**Comment by NicolasRannou** [comment]
fsl was missing

**Comment by NicolasRannou** [comment]
packages/scripts/dcmanon_meta.bash and dicom_dirSend.bash must be modified to point to right certificate for anonymization

**Comment by NicolasRannou** [comment]
keys in anonymize_keys were not correct, error updated in wiki CA_cert.pem instead of CA_cert.cer

**Comment by NicolasRannou** [comment]
in wiki error: CA_cert.pem instead of CA_cert.cer

**Comment by rudolphpienaar** [comment]
Ugh... there are so many little niggling things!!

**Comment by NicolasRannou** [comment]
missing files for the mri_deface in freesurfer directory on sun...:

```
GCAread(/lustre/SCRATCH5/cubic/chris/packages/freesurfer/stable/average/talairach_mixed_with_skull.gca): could not open file
```
